%ANIMRAD.M adds the animation control radio buttons to the ant simulation.
%

%----------------------------------------------------------------------------------

uiANIM=uicontrol(fig,'style','radio',...
                'position',[0.025,0.135,0.2,0.025],...
                'units','normalized',...
                'string','Animated',...
                'value',1,...
                'backgroundcolor',[0.5 0.2 0.2],...
                'foregroundcolor',[1 1 1],...                
                'callback',...
                ['if (get(uiANIM,''value'')==1), set(uiNOANIM,''value'',0);',...
                'set(StatusBar,''string'',''Enabling animation.''); else,',...
                'set(StatusBar,''string'',''Disabling animation.'');',...
                'set(uiNOANIM,''value'',1);end;']);
                 
uiNOANIM=uicontrol(fig,'style','radio',...
                'position',[0.025,0.11,0.2,0.025],...
                'units','normalized',...
                'string','Static',...
                'value',0,...
                'backgroundcolor',[0.5 0.2 0.2],...
                'foregroundcolor',[1 1 1],...                      
                'callback',...
                ['if (get(uiNOANIM,''value'')==1), set(uiANIM,''value'',0);',...
                'set(StatusBar,''string'',''Disabling animation.'');',...
                'else,set(StatusBar,''string'',''Enabling animation.'');',...
                'set(uiANIM,''value'',1);end']);                
           
