% ANTDRAW.M
%
% Draws the GUI for the digital ant simulation and sets
% default simulation parameters.
%

initants;                       % script containing initializations of variables.

EATING_COLOR=[1 1 0];
TALKING_COLOR=[1 0 0];
NOTHING_COLOR=[0 0 1];
MOVING_COLOR=[1 0 1];
LISTEN_COLOR=[1 1 1];

fig=gcf;
clf;
set(fig,'units','normalized','position',[0.025,0.075,0.7,0.9],...
        'backingstore','off','nextplot','new','color',[0.05 0.05 0.15],...
        'name','Q-Learning for Communicating Ants','visible','off');


b=0.9;
bh=0.025;
h1=0.0225;
h2=0.08;
ib=0.46;
ll=0.25;
w1=0.0125/2;
w2=0.225;
bb=ib+3*w1+2*h1+0.0125;
lb=bb+0.0125*3+3*bh+2*h1+0.0125;

%sliders frame
Frames(1)=uicontrol(fig,'style','frame',...
                        'position',[0.0125 b-11*h2-0.5*h1 0.225 12*h2+0.0125],...
                        'units','normalized',...
                        'backgroundcolor',[0.5 0.2 0.2],...
                        'foregroundcolor',[0.3 0.3 0.3]);

%button/info frame 
Frames(2)=uicontrol(fig,'style','frame',...
                      'position',[0.25, bb, 0.225, 0.0125*3+3*bh+2*h1],...
                      'units','normalized',...
                      'backgroundcolor',[0.5 0.2 0.2],...
                      'foregroundcolor',[0.3 0.3 0.3]);                        

%status bar frame                      
Frames(3)=uicontrol(fig,'style','frame',...
                      'position',[0.249,0.01,0.750,0.085],...
                      'units','normalized',...
                      'backgroundcolor',[0 0 0.7],...
                      'foregroundcolor',[0.6 0.6 0.6]);
                      
StatusBar=uicontrol(fig,'style','text','horizontal','Left',...
        'string','Set program parameters using the sliders, then press the <S T A R T> button to begin.',...
        'position',[0.25,0.0125,0.75-0.0125,0.075],'units','normalized',...
        'backgroundcolor',[0 0 0.7],'foregroundcolor',[1 1 0]);
        
RandomBox=uicontrol(fig,'style','text','horizontal','center',...
        'string','Using random actions',...
        'position',[0.25+0.0125,bb+0.025+3*bh+h1,0.2,h1],'units','normalized',...
        'backgroundcolor',[0 0 0.7],'foregroundcolor',[1 1 0]);                

StepBox=uicontrol(fig,'style','text','horizontal','center',...
        'string','STEP=1',...
        'position',[0.25+0.0125,bb+0.025+3*bh,0.2,h1],'units','normalized',...
        'backgroundcolor',[0 0 0.7],'foregroundcolor',[1 1 0]);

%----------------------------------------------------------------------------------

%Legend frame
Frames(4)=uicontrol(fig,'style','frame',...
                      'position',[ll,lb,w2,8*w1+7*h1],...
                      'units','normalized',...
                      'backgroundcolor',[0.3 0.3 0.3],...
                      'foregroundcolor',[0.6 0.6 0.6]);
                              
Legend(1)=uicontrol(fig,'style','text','horizontal','center',...
        'string','+ Food',...
        'position',[ll+w1,lb+w1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 0]);
Legend(2)=uicontrol(fig,'style','text','horizontal','center',...
        'string','* Eating',...
        'position',[ll+w1,lb+2*w1+h1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0],'foregroundcolor',EATING_COLOR);
Legend(3)=uicontrol(fig,'style','text','horizontal','center',...
        'string','* Moving',...
        'position',[ll+w1,lb+3*w1+2*h1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0],'foregroundcolor',MOVING_COLOR);
Legend(4)=uicontrol(fig,'style','text','horizontal','center',...
        'string','* Talking',...
        'position',[ll+w1,lb+4*w1+3*h1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0],'foregroundcolor',TALKING_COLOR);
Legend(5)=uicontrol(fig,'style','text','horizontal','center',...
        'string','* Listening',...
        'position',[ll+w1,lb+5*w1+4*h1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0],'foregroundcolor',LISTEN_COLOR);        
Legend(6)=uicontrol(fig,'style','text','horizontal','center',...
        'string','--- Communication',...
        'position',[ll+w1,lb+6*w1+5*h1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0],'foregroundcolor',[0 0.5 0]);                        
Legend(7)=uicontrol(fig,'style','text','horizontal','center',...
        'string','*   Inactive',...
        'position',[ll+w1,lb+7*w1+6*h1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0],'foregroundcolor',NOTHING_COLOR);                       
                                       
%----------------------------------------------------------------------------------

% information frame
Frame(5)=uicontrol(fig,'style','frame',...
                    'position',[ll,ib,w2,3*w1+2*h1],...
                    'units','normalized',...
                    'backgroundcolor',[0.3 0.3 0.3],...
                    'foregroundcolor',[0.6 0.6 0.6]);
                    
QTsize=uicontrol(fig,'style','text','horizontal','left',...
        'string',['QTable size:  ',num2str((1+NEnergyStates)*2),' X ',num2str(NActions)],...
        'position',[ll+w1,ib+2*w1+h1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0.7],'foregroundcolor',[1 1 0]);                                                 

Lifetime=uicontrol(fig,'style','text','horizontal','left',...
        'string',['Base lifespan:  ',num2str(round((NEnergyStates-0.5)/ENCOST)),' cycles'],...
        'position',[ll+w1,ib+w1,w2-2*w1,h1],'units','normalized',...
        'backgroundcolor',[0 0 0.7],'foregroundcolor',[1 1 0]);                            
                   
%----------------------------------------------------------------------------------
                    
Sliders(1,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b,0.2,0.02],...
                'units','normalized',...
                'max',100,'min',2,'value',NAnts,...         
                'callback',...
                ['NAnts=round(get(Sliders(1,1),''value''));',...
                'set(Sliders(1,2),''string'',num2str(NAnts));',...
                'set(StatusBar,''string'',[''NAnts set to '',num2str(NAnts)]);']);
                            
Sliders(1,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(NAnts),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(1,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Number of Ants',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
%----------------------------------------------------------------------------------


Sliders(2,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-h2,0.2,0.02],...
                'units','normalized',...
                'max',1,'min',0.01,'value',ENCOST,...         
                'callback',['ENCOST=ECres*round(get(Sliders(2,1),''value'')/ECres);',...
                            'set(Sliders(2,2),''string'',num2str(ENCOST));',...
                            'set(StatusBar,''string'',[''ENCOST set to '',num2str(ENCOST)]);',...
                            'NTotalStates=guifix(Sliders,Lifetime,QTsize,NActions,ECres);']);
                            
Sliders(2,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(ENCOST),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(2,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Standard Energy Cost',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
%----------------------------------------------------------------------------------
                
                                
Sliders(3,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-2*h2,0.2,0.02],...
                'units','normalized',...
                'max',0.995,'min',0.5,'value',GAMMA,...         
                'callback',['GAMMA=0.005*round(get(Sliders(3,1),''value'')/0.005);',...
                            'set(Sliders(3,2),''string'',num2str(GAMMA));',...
                            'set(StatusBar,''string'',[''GAMMA set to '',num2str(GAMMA)]);']);
                            
Sliders(3,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-2*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(GAMMA),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(3,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-2*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Gamma',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);                                
                
%----------------------------------------------------------------------------------
                
Sliders(4,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-3*h2,0.2,0.02],...
                'units','normalized',...
                'max',0.995,'min',0.5,'value',BETAEXP,...         
                'callback',['BETAEXP=0.005*round(get(Sliders(4,1),''value'')/0.005);',...
                            'set(Sliders(4,2),''string'',num2str(BETAEXP));',...
                            'set(StatusBar,''string'',[''BETAEXP set to '',num2str(BETAEXP)]);']);
                            
Sliders(4,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-3*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(BETAEXP),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(4,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-3*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Beta exponent',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                                                
%----------------------------------------------------------------------------------
                
Sliders(5,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-4*h2,0.2,0.02],...
                'units','normalized',...
                'max',200,'min',3,'value',WorldSize,...         
                'callback',...
                ['WorldSize=round(get(Sliders(5,1),''value''));',...
                'set(Sliders(5,2),''string'',num2str(WorldSize));',...
                'set(StatusBar,''string'',[''WorldSize set to '',num2str(WorldSize)]);',...
                'MASKSIZE=chckmask(Sliders,StatusBar);']);
                            
Sliders(5,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-4*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(WorldSize),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(5,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-4*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','World Size',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);                                                

%----------------------------------------------------------------------------------
                
Sliders(6,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-5*h2,0.2,0.02],...
                'units','normalized',...
                'max',150,'min',3,'value',MaxFoodSize,...         
                'callback',['MaxFoodSize=round(get(Sliders(6,1),''value''));',...
                            'set(Sliders(6,2),''string'',num2str(MaxFoodSize));',...
                            'set(StatusBar,''string'',[''MaxFoodSize set to '',num2str(MaxFoodSize)]);']);
                            
Sliders(6,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-5*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(MaxFoodSize),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(6,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-5*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Max Food Size',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                                                                                
%----------------------------------------------------------------------------------
                
Sliders(7,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-6*h2,0.2,0.02],...
                'units','normalized',...
                'max',0.3,'min',0.0025,'value',FoodDensity,...         
                'callback',['FoodDensity=0.0025*round(get(Sliders(7,1),''value'')/0.0025);',...
                            'set(Sliders(7,2),''string'',num2str(FoodDensity));',...
                            'set(StatusBar,''string'',[''FoodDensity set to '',num2str(FoodDensity)]);']);
                            
Sliders(7,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-6*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(FoodDensity),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(7,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-6*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Food Density',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                                                                                                                                                          
%----------------------------------------------------------------------------------

Sliders(8,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-7*h2,0.2,0.02],...
                'units','normalized',...
                'max',200,'min',2,'value',NEnergyStates,...         
                'callback',['NEnergyStates=round(get(Sliders(8,1),''value''));',...
                            'set(Sliders(8,2),''string'',num2str(NEnergyStates));',...
                            'set(StatusBar,''string'',[''NEnergyStates set to '',num2str(NEnergyStates)]);',...
                            'NTotalStates=guifix(Sliders,Lifetime,QTsize,NActions,ECres);']);
                            
Sliders(8,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-7*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(NEnergyStates),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(8,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-7*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Number of Energy States',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                                                                                                                                                          
%----------------------------------------------------------------------------------

Sliders(9,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-8*h2,0.2,0.02],...
                'units','normalized',...
                'max',MASKSIZE,'min',2,'value',MASKSIZE,...         
                'callback',['MASKSIZE=round(get(Sliders(9,1),''value''));',...
                            'set(Sliders(9,2),''string'',num2str(MASKSIZE));',...
                            'set(StatusBar,''string'',[''MASKSIZE set to '',num2str(MASKSIZE)]);']);
                            
Sliders(9,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-8*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(MASKSIZE),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(9,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-8*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Communication Radius',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);                
                                                                                                                                                                                                                                       
%----------------------------------------------------------------------------------

Sliders(10,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-9*h2,0.2,0.02],...
                'units','normalized',...
                'max',1,'min',0,'value',BONUS,...         
                'callback',['BONUS=0.025*round(get(Sliders(10,1),''value'')/0.025);',...
                            'set(Sliders(10,2),''string'',num2str(BONUS));',...
                            'set(StatusBar,''string'',[''BONUS set to '',num2str(BONUS)]);']);
                            
Sliders(10,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-9*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(BONUS),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(10,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-9*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Cooperation benefit',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);

%----------------------------------------------------------------------------------

Sliders(11,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-10*h2,0.2,0.02],...
                'units','normalized',...
                'max',1,'min',0,'value',BASEFOOD,...         
                'callback',['BASEFOOD=0.025*round(get(Sliders(11,1),''value'')/0.025);',...
                            'set(Sliders(11,2),''string'',num2str(BASEFOOD));',...
                            'set(StatusBar,''string'',[''BASEFOOD set to '',num2str(BASEFOOD)]);']);
                            
Sliders(11,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-10*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(BASEFOOD),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(11,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-10*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','1-ant food allowance',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);                
                
%----------------------------------------------------------------------------------

Sliders(12,1)=uicontrol(fig,'style','slider',...
                'position',[0.025,b-11*h2,0.2,0.02],...
                'units','normalized',...
                'max',9,'min',0,'value',SAMEPLACE,...         
                'callback',['SAMEPLACE=round(get(Sliders(12,1),''value''));',...
                            'set(Sliders(12,2),''string'',num2str(SAMEPLACE));',...
                            'set(StatusBar,''string'',[''SAMEPLACE set to '',num2str(SAMEPLACE)]);',...
                            'NTotalStates=guifix(Sliders,Lifetime,QTsize,NActions,ECres);']);
                            
Sliders(12,2)=uicontrol(fig,'style','text',...
                'position',[0.025,b-11*h2+h1,0.2,0.025],...
                'units','normalized',...
                'string',num2str(SAMEPLACE),...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);
                
Sliders(12,3)=uicontrol(fig,'style','text',...
                'position',[0.025,b-11*h2+2*h1,0.2,0.025],...
                'units','normalized',...
                'string','Co-location quantization',...
                'backgroundcolor',[0 0 0],...
                'foregroundcolor',[1 1 0]);                
                                                                                                                                                                                                                                                       
%----------------------------------------------------------------------------------


uiSTART=uicontrol(fig,'style','pushbutton',...
                'position',[0.25+0.0125,bb+0.0125+2*bh,0.2,bh],...
                'units','normalized',...
                'string','S  T  A  R  T','callback',...
                ['set(StatusBar,''string'',''Starting ANTEXEC.M...'');',...
                'axes(ANTAX);cla;axes(METRAX);cla;',...
                'antexec;']);
                
uiRESET=uicontrol(fig,'style','pushbutton',...
                'position',[0.25+0.0125,bb+0.0125,0.1,bh],...
                'units','normalized',...
                'string','Reset All','callback',...
                'delete(fig);clear antdraw,antdraw;');

uiCLOSE=uicontrol(fig,'style','pushbutton',...
                'position',[0.25+0.125-0.0125,bb+0.0125,0.1,bh],...
                'units','normalized',...
                'string','Close','callback','close(fig)');
                
uiCLEAR=uicontrol(fig,'style','pushbutton',...
                'position',[ll+0.0125,bb+0.0125+bh,0.2,bh],...
                'units','normalized',...
                'string','Clear graphs','callback',['tempax=gca;axes(ANTAX);cla;axes(METRAX);cla;',...
                'axes(gca);NAnts=round(get(Sliders(1,1),''value''));']);                

%----------------------------------------------------------------------------------
Frames(6)=uicontrol(fig,'style','frame',...
                    'position',[ll,lb+8*w1+7*h1+0.0125,w2,2*bh+0.0125],...
                    'units','normalized',...
                    'backgroundcolor',[0.5 0.2 0.2],...
                    'foregroundcolor',[0.3 0.3 0.3]);
                    
anim(1)=uicontrol(fig,'style','radio',...
                'position',[ll+0.0125,lb+8*w1+7*h1+1.5*0.0125,0.125,bh],...
                'units','normalized','string','Animated','callback',...
                'animated=toggle(anim,1);','value',1,...
                'backgroundcolor',[0.5 0.2 0.2],...
                'foregroundcolor',[1 1 0]);

anim(2)=uicontrol(fig,'style','radio',...
                'position',[ll+0.0125,lb+8*w1+7*h1+1.5*0.0125+bh,0.125,bh],...
                'units','normalized','string','Invisible','callback',...
                'animated=toggle(anim,2);','value',0,...
                'backgroundcolor',[0.5 0.2 0.2],...
                'foregroundcolor',[1 1 0]);                     

%----------------------------------------------------------------------------------

ANTAX=axes('position',[0.4875, 0.48, 0.5, 0.5]);
set(ANTAX,'color',[0 0 0],'drawmode','fast','YDir','reverse','box','on','tickdir','out',...
'xticklabels',[],'yticklabels',[]);
axis('image');
          
METRAX=axes('position',[0.35 0.125 0.6 0.3],'color',[0 0 0],...
        'tickdir','out','drawmode','fast','box','on','fontsize',8);

%----------------------------------------------------------------------------------

set(fig,'visible',animated);
NTotalStates=guifix(Sliders,Lifetime,QTsize,NActions,ECres);        
clear b, clear h1, clear h2, clear lb, clear ll, clear w1, clear w2, clear bb,
